### ISSUE TITLE
Update eslint to latest of v8

### ISSUE THREAD

**Issue by Lonli-Lokli** [josejulio/openapi2typescript#5]
I have eslint v8 and cannot run `npx openapi2typescript-cli -i libs/api/v1.json -o libs/api/schema`

gettings error
```
npx: installed 124 in 24.005s
(node:1732) UnhandledPromiseRejectionWarning: Error: libs\.eslintrc.json » ../.eslintrc.json#overrides[0] » plugin:unicorn/recommended:
        Environment key "es2022" is unknown

    at C:\Users\testuser\AppData\Roaming\npm-cache\_npx\1732\node_modules\openapi2typescript-cli\node_modules\@eslint\eslintrc\lib\shared\config-validator.js:175:23
    at Array.forEach (<anonymous>)
    at ConfigValidator.validateEnvironment (C:\Users\testuser\AppData\Roaming\npm-cache\_npx\1732\node_modules\openapi2typescript-cli\node_modules\@eslint\eslintrc\lib\shared\config-validator.js:169:34)
    at ConfigValidator.validateConfigArray (C:\Users\testuser\AppData\Roaming\npm-cache\_npx\1732\node_modules\openapi2typescript-cli\node_modules\@eslint\eslintrc\lib\shared\config-validator.js:319:18)
    at CascadingConfigArrayFactory._finalizeConfigArray (C:\Users\testuser\AppData\Roaming\npm-cache\_npx\1732\node_modules\openapi2typescript-cli\node_modules\@eslint\eslintrc\lib\cascading-config-array-factory.js:493:23)
    at CascadingConfigArrayFactory.getConfigArrayForFile (C:\Users\testuser\AppData\Roaming\npm-cache\_npx\1732\node_modules\openapi2typescript-cli\node_modules\@eslint\eslintrc\lib\cascading-config-array-factory.js:299:21)
    at CLIEngine.isPathIgnored (C:\Users\testuser\AppData\Roaming\npm-cache\_npx\1732\node_modules\openapi2typescript-cli\node_modules\eslint\lib\cli-engine\cli-engine.js:967:18)
    at CLIEngine.executeOnText (C:\Users\testuser\AppData\Roaming\npm-cache\_npx\1732\node_modules\openapi2typescript-cli\node_modules\eslint\lib\cli-engine\cli-engine.js:878:38)
```

**Comment by Lonli-Lokli** [comment]
I actually agree, I disabled eslint and use only prettier too

**Comment by Lonli-Lokli** [comment]
@josejulio 
Did you publish this fix?
I've installed 0.6.1 but still gettin same
`  'import * as z from \'zod\';\n'`

I am looking into node_modules\openapi2typescript-cli\lib\main.js and this code is still there

**Comment by josejulio** [comment]
Hello - haven't been able to do that - sorry.  Will look for some time to do it early next week or hopefully this week.
